name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [apps/frontend, apps/backend, shared]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --workspace ${{ matrix.folder }}
      - name: Build
        run: npm run build --workspace ${{ matrix.folder }}
      - name: Lint
        run: npm run lint --workspace ${{ matrix.folder }} || true
